<a href="https://colab.research.google.com/github/avpakh/TMS-DS1/blob/main/%22%D0%94%D0%BE%D0%BC%D0%B0%D1%88%D0%BD%D0%B5%D0%B5_%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5_11_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Добро пожаловать в мир Линейной Алгебры

Пользуйтесь [документацией](https://numpy.org/doc/1.17/reference/index.html) чтобы найти нужный метод для расчетов.

In [46]:
import numpy as np
import numpy.linalg as LA

## Task 1
Найдите сумму всех елементов массива. [Подсказка](https://docs.scipy.org/doc/numpy/reference/generated/numpy.sum.html).

In [ ]:
A = np.array([[1,13,4,5, -6],[-9,4,12,0,2],[45,4,3,2,1], [3,-9,15,6,22],[3,5,0,-7,12]])
print (A)


[[ 1 13  4  5 -6]
 [-9  4 12  0  2]
 [45  4  3  2  1]
 [ 3 -9 15  6 22]
 [ 3  5  0 -7 12]]


In [ ]:
ans1 = A.sum()
print ('Сумма всех элементов',ans1) 


Сумма всех элементов 131


## Task 2
Посчитайте разницу между матрицами m1 и m2.

In [ ]:
m1 = np.array([[-7, -6,  3, -5],
       [ 7,  0,  4,  0],
       [ 6, -1,  1,  1]])
m2 = np.array([[  6,  -7,  -3,  -9],
       [ -8,   1,  -4,   2],
       [-10,   1,  -7,   9]])

In [ ]:
ans2 = np.subtract(m1,m2)

print (ans2)

[[-13   1   6   4]
 [ 15  -1   8  -2]
 [ 16  -2   8  -8]]


## Task 3
Найдите суму всех елементов матрицы модуль которых больше 5. Используя цикл $\textit{for}$, или numpy методы ([подсказка](https://docs.scipy.org/doc/numpy/reference/generated/numpy.where.html)).

In [ ]:
b = np.array([[ -6,  -7,  -5,   0],
       [-15,   2, -13,  -5],
       [  8,   4,  10,   8],
       [ -1,  -9,   7,  -4]])

In [ ]:
ans3 = np.where(abs(b)>5,b,0)
print ('Промежуточная матрица',ans3)
sum_array= ans3.sum()
print ('Результат вычислений:',sum_array)


Промежуточная матрица [[ -6  -7   0   0]
 [-15   0 -13   0]
 [  8   0  10   8]
 [  0  -9   7   0]]
Результат вычислений -17


## Task 4
Найдите произведение двух матриц. Лучше использовать $\textit{matmul}$.

In [ ]:
n = np.array([[ -4,  -1,   3,  -7,   6,  -9,   5,  -9,  -7,   0],
       [-12,   3, -12,  -7,   2,  -4,   8,  13,   9,   3],
       [ -2,  -1, -15, -10,   7,   5,   7, -13,  -9,   6],
       [  7,  11,  -5,  -6,  -9,  -1,   3,  10, -15,  -6],
       [ -3,  -4,   4, -13,   4, -13,  10,  -6,  -8,  13],
       [  7, -13,  -4,   3,   4,  13, -13,   4,  -9, -10],
       [ -5,  13,  -9, -15,  11,   2,   7, -14, -14,   2],
       [ -4,  -6,  12,  10,  13,  -3,  12, -15,   5,  -2],
       [ -1,   8,   3,   7,  11,  -3,   6,  12,  12, -13],
       [ 12,  11,  12,  11,   1, -14,   2,   6,  -9,  -3]])
z = np.array([[-15,   5, -15,  10,  -3,  12,  -6, -15,   6,   3],
       [ 12,  -4,   6, -11,   5,   3,   3,  12, -15,  -6],
       [-11, -11, -10,   9,  -8, -14, -14,   7,  -2,  11],
       [  5,  -4,  11,   0,   8,  -9, -15, -11,   7, -10],
       [ -6,  -9,  -3, -13, -11,  -9,   7,  -7,   9,   4],
       [ 10,  12,   4,  -7,   1,   0,  -1,  11,  -4,  11],
       [-14,   2,  -8,  11,  -9,   5, -14,  10,  -6,  -9],
       [ -5,  10, -10,  -1,  -9, -12,  12,  14,   4,   2],
       [ -1, -13,  10,  11,  12, -14,   9,  12,  12,  -5],
       [  2,   6, -13,  -5,  -2,  -2,   0,  14,   7,  14]])

In [ ]:
ans4 = np.matmul(n, z)
print (ans4)

[[-164 -172 -127  -30 -196  147 -106 -155 -124   -6]
 [  81   69   76 -100  -22 -170  497  563   25 -201]
 [ 129  233  -31 -309  -97  515   78 -107 -154   58]
 [   7  404 -228  -84 -161  439   32   16 -432 -103]
 [-342  -41 -495   52 -362  185  -98   99  -58  182]
 [  55  310   34 -162  -68   71   94 -529  166  214]
 [ 199   75  -29 -504 -196  536  103   12 -473   31]
 [-304 -524   93  198  -89 -267 -521 -220  155 -116]
 [-165 -335  186   58  -41 -448  131  135   93 -349]
 [-326 -174 -299  124 -188  -29 -388 -292  -92 -161]]


## Task 5
Создайте идентичную матрицу размера A и отнимите ее от матрицы А.

In [ ]:
A = np.array([[  7,   8, -15,   8,  11,   7],
       [ -5,  -9,  13,  -3, -15, -11],
       [ -3,   0,  10,  -5,   3,  -8],
       [ 10,   1,   7, -11,  10,  -3],
       [ 11,   9,  -6, -14,  10, -11],
       [  6,  -4,  -4,  -9,  -6,  -7]])
A

array([[  7,   8, -15,   8,  11,   7],
       [ -5,  -9,  13,  -3, -15, -11],
       [ -3,   0,  10,  -5,   3,  -8],
       [ 10,   1,   7, -11,  10,  -3],
       [ 11,   9,  -6, -14,  10, -11],
       [  6,  -4,  -4,  -9,  -6,  -7]])

In [ ]:
ident = np.eye(np.shape(A)[0])
print (ident)

ans5 = np.subtract(A, ident)
print ('Результирующая матрица:',ans5)


[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
Результирующая матрица: [[  6.   8. -15.   8.  11.   7.]
 [ -5. -10.  13.  -3. -15. -11.]
 [ -3.   0.   9.  -5.   3.  -8.]
 [ 10.   1.   7. -12.  10.  -3.]
 [ 11.   9.  -6. -14.   9. -11.]
 [  6.  -4.  -4.  -9.  -6.  -8.]]


## Task 6
Найдите решение системы уровнений Ax = b, используя обратную матрицу.

In [ ]:
A = np.array([[ 0, -2,  0, -2],
       [-2,  0, -4,  4],
       [-1, -5, -2,  2],
       [ 3, 1, 2,  1]])

In [ ]:
b = np.array([-4,  1,  4,  2])

# X = [x1,x2,x3,x4]

# 1. Поиск обратной матрицы A-1 

Az = np.linalg.inv(A)

print (Az)

# X = Az*b

ans6 = np.matmul(Az, b)

print ('Результирующая матрица',ans6)



[[ 7.50000000e-01  3.50000000e-01 -2.00000000e-01  5.00000000e-01]
 [ 1.18952467e-17  1.00000000e-01 -2.00000000e-01 -3.96508223e-18]
 [-8.75000000e-01 -5.25000000e-01  3.00000000e-01 -2.50000000e-01]
 [-5.00000000e-01 -1.00000000e-01  2.00000000e-01  1.58603289e-18]]
[-2.45  -0.7    3.675  2.7  ]


## Task 7
Напишите функцию скалярного умножения двух векторов, а потом используя ее создайте функцию умножения двух матриц.

In [48]:
m = np.array([1,  1]) # 1-й вектор
n = np.array([1,  2]) # 2-й вектор


def scal_mult(_v1,_v2): # функция скалярного произведения векторов
  dim = np.shape(_v1)[0]
  s=0
  for i in range(dim):
    s+=_v1[i]*_v2[i]
  return s
  
z = scal_mult(m,n)

# Произведение матриц AB состоит из всех возможных комбинаций скалярных произведений 
# вектор-строк матрицы A и вектор-столбцов матрицы B. 
# Элемент матрицы AB с индексами i, j есть скалярное произведение i-ой вектор-строки матрицы A 
# и j-го вектор-столбца матрицы B.

def matrix_mult(_a, _b): # функция умножения матрицы
    # Создать пустую матрицу с размерами

    result_array = np.zeros((np.shape(_a)[0], np.shape(_b)[1]))

    size_i = np.shape(_a)[0]
    size_j =  np.shape(_b)[1]

    for i in range(size_i):
        print (i)
        for j in range(size_j):
            result_array[i, j] = scal_mult(_a[i,:], _b[:, j])

    return result_array


a = np.array([[ 2, -3],
       [4, 5]])
b = np.array([[ 1, -3,-2],
       [2,4, -1]])


t  = matrix_mult(a,b)
print (t)


0
1
[[ -4. -18.  -1.]
 [ 14.   8. -13.]]
