<a href="https://colab.research.google.com/github/avpakh/TMS-DS1/blob/main/%D0%94%D0%97_%D0%9B%D0%B8%D0%BD%D0%B5%D0%B9%D0%BD%D0%B0%D1%8F_%D0%90%D0%BB%D0%B3%D0%B5%D0%B1%D1%80%D0%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [92]:
import numpy as np
import numpy.linalg as LA

1. Какой ранг матрицы ?


In [ ]:
A = np.array([[1,4,5],[-5,8,9],[-12,8,8]])

rank_A = LA.matrix_rank(A)

print ('Ранг матрицы = ', rank_A)


Ранг матрицы =  2


2.  Какой ранг матрицы ?

In [ ]:
A = np.array([[3,-1,1,9],[-3,4,1,1],[6,5,2,8],[1,1,1,1]])

rank_A = LA.matrix_rank(A)

print ('Ранг матрицы = ', rank_A)

Ранг матрицы =  4


3. Сколько векторов в базиcе решений ?
   
   Ax = 0 
   
   Решение:
   1. Привести матрицу A к эшелонной форме [EF]
   2. Решить уравнение [EF][x1,x2,x3,x4,x5] = [0,0] 
   3. Найти кол-во векторов в решении.




In [ ]:
from sympy import *
m = Matrix( [[4,5,7,-3,1],[11,8,-4,2,0]])

M_rref = m.rref()
print("Представление матрицы в эшелонной форме : {}".format(M_rref[0]))

t = M_rref[0]
# преобразование в 
A_= np.array(t).astype(np.float64)

NoC = m.shape[1]
# Rank of A
rank = m.rank()
  
# Nullity of the Matrix
nullity = NoC - rank
  
print("Ответ - Количество (размерность) нулевого пространства A  - есть количество векторов : ", nullity)





Представление матрицы в эшелонной форме : Matrix([[1, 0, -76/23, 34/23, -8/23], [0, 1, 93/23, -41/23, 11/23]])
Ответ - Количество (размерность) нулевого пространства A  - есть количество векторов :  3


Сколько векторов в базиcе решений ?

In [ ]:
from sympy import *
m = Matrix( [[0,2,7,-1],[-1,2,5,5],[-4,13,0,6]])

M_rref = m.rref()
print("Представление матрицы в эшелонной форме : {}".format(M_rref[0]))

t = M_rref[0]
# преобразование в 
A_= np.array(t).astype(np.float64)

NoC = m.shape[1]

# Rank of A
rank = m.rank()
  
# Nullity of the Matrix
nullity = NoC - rank
  
print("Ответ - Количество (размерность) нулевого пространства A  - есть количество векторов : ", nullity)


Представление матрицы в эшелонной форме : Matrix([[1, 0, 0, -496/75], [0, 1, 0, -118/75], [0, 0, 1, 23/75]])
Ответ - Количество (размерность) нулевого пространства A  - есть количество векторов :  1


5. Имеет ли эта система решение ? Использовать теорему Кронекера-Капелли




In [ ]:
# основная матрица (A)

A = np.array([[4,1,-8,5],[-3,1,4,7],[1,2,-4,12],[1,1,1,1]])

rank_A = LA.matrix_rank(A)

print ('Ранг основной матрицы', rank_A)

# раcширенная матрица (A|B)

A_B = np.array([[4,1,-8,5,2],[-3,1,4,7,1],[1,2,-4,12,1],[1,1,1,1,2]])

rank_AB = LA.matrix_rank(A_B)

print ('Ранг расширенной матрицы', rank_AB)

if rank_A == rank_AB:
  print ('Система уравнений разрешима')
else:
  print ('Система уравнений не имеет решения')




Ранг основной матрицы 3
Ранг расширенной матрицы 4
Система уравнений не имеет решения


6. Найти длину вектора в Эвклидовом пространстве


In [ ]:
AB = np.array([1,-7,3])

len_AB = np.linalg.norm(AB)

print ('Длина вектора - ', round(len_AB,4))

Длина вектора -  7.6811


7. Есть ли A решением системы линейных уравнений ?

  Решение  1. Найти ранг СЛАУ и определить размерность векторного пространства (число векторов  в любой фундаментальной системе решений для Ax=0 равно n-r, r- ранг A)
            


In [4]:
A = np.array([[-10,13,12,0],[3,-3,0,3],[-17,23,24,3]])

M = np.array([[1,-2,3,-3],[4,4,-1,0],[5,14,-11,9],[-7,-10,5,-3]])

rank_M = LA.matrix_rank(M)

print ('Ранг матрицы М', rank_M)

NoC = M.shape[1]


print ('Число векторов решений', NoC - rank_M)

rank_A = LA.matrix_rank(A)

print ('Ранг матрицы A', rank_A)

if rank_A == (NoC -rank_M):
  print ('строки А являются решением СЛАУ')
else:
  print ('строки А не являются решением СЛАУ')


Ранг матрицы М 2
Число векторов решений 2
Ранг матрицы A 2
строки А являются решением СЛАУ


8. Какое решение для системы Ax = b где 

In [33]:

A = np.array([[1,0,3,1],[5,-1,1,0],[3,7,-1,8],[-3,-2,-1,-3]])
A_b = np.array([[1,0,3,1,1],[5,-1,1,0,1],[3,7,-1,8,1],[-3,-2,-1,-3,-1]])
b =  np.array([1,1,1,-1])

rank_A = LA.matrix_rank(A)
rank_A_b = LA.matrix_rank(A_b)


print ('Ранг матрицы A', rank_A)

print ('Ранг матрицы расширенной A_b', rank_A_b)

if rank_A == rank_A_b:
   print ('Cистема Ax = b  является совместной')

det_A = round(np.linalg.det(A), 0)
print('Определитель равен:', round(np.linalg.det(A), 0))
if det_A == 0:
  print ('Определитель матрицы A равен 0. Таким образом, матрицы A - вырожденная, т.е. система имеет бесконечное множество решений.')
  


 













Ранг матрицы A 3
Ранг матрицы расширенной A_b 3
Cистема Ax = b  является совместной
Определитель равен: 0.0
Определитель матрицы A равен 0. Таким образом, матрицы A - вырожденная, т.е. система имеет бесконечное множество решений.


9. Какая размерность решения ?



In [37]:
from sympy import *
m = Matrix( [[1,-3,1,-2,9],[0,1,-3,-5,4],[-2,7,-5,-1,-14],[1,-5,7,8,1]])

M_rref = m.rref()
print("Представление матрицы в эшелонной форме : {}".format(M_rref[0]))

t = M_rref[0]
# преобразование в 
A_= np.array(t).astype(np.float64)

NoC = m.shape[1]

# Rank of A
rank = m.rank()
  
# Nullity of the Matrix
nullity = NoC - rank
  
print("Ответ - Количество (размерность)  - есть количество векторов : ", nullity)

Представление матрицы в эшелонной форме : Matrix([[1, 0, -8, -17, 21], [0, 1, -3, -5, 4], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]])
Ответ - Количество (размерность)  - есть количество векторов :  3


In [ ]:
10. Какая декомпозиция матрицы 
    A = QR


In [54]:



A = np.array([[1,1,1],[2,2,2],[3,3,3],[1,2,3]])

Q,R = LA.qr(A)

print ('ортогональная матрица',Q)
print ('верхняя треугольная матрица',R)

print ('Максимальный ранг декомпозиции матрицы -', max(LA.matrix_rank(Q),LA.matrix_rank(R)))







ортогональная матрица [[-2.58198890e-01 -6.90065559e-02  9.46091996e-01]
 [-5.16397779e-01 -1.38013112e-01  1.24424396e-02]
 [-7.74596669e-01 -2.07019668e-01 -3.23658958e-01]
 [-2.58198890e-01  9.66091783e-01 -1.23194190e-15]]
верхняя треугольная матрица [[-3.87298335e+00 -4.13118224e+00 -4.38938113e+00]
 [ 0.00000000e+00  9.66091783e-01  1.93218357e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.06261527e-15]]
Максимальный ранг декомпозиции матрицы 3


11. Имеет ли эта система решение с использованием Кронекера-Капелли

Система линейных алгебраических уравнений совместна тогда и только тогда, когда ранг её основной матрицы равен рангу её расширенной матрицы.

In [56]:
A = np.array([[-8,-1,5],[-5,2,7],[0,3,8]])
A_b =  np.array([[1,1,1],[2,2,2],[3,3,3],[1,2,3]])

rank_A = LA.matrix_rank(A)
rank_Ab = LA.matrix_rank(A_b)

print ('Ранг матрицы A', rank_A)
print ('Ранг расширенной матрицы Ab', rank_Ab)

if rank_A == rank_Ab:
  print ('Система уравнений разрешима')
else:
  print ('Система уравнений не имеет решения')

Ранг матрицы A 3
Ранг расширенной матрицы Ab 2
Система уравнений не имеет решения


12. Найти угол между векторами  x и у





In [70]:
vector1 = [1,-3,0]
vector2 = [0,1,-7]

unit_vector1 = vector1 / np.linalg.norm(vector1)
unit_vector2 = vector2 / np.linalg.norm(vector2)

dot_product = np.dot(unit_vector1, unit_vector2)

angle = np.arccos(dot_product) #angle in radian

print ('Угол между векторами (numpy) :', np.degrees(angle))

import math
def dotproduct(v1, v2):
  return sum((a*b) for a, b in zip(v1, v2))

def length(v):
  return math.sqrt(dotproduct(v, v))

def _angle(v1, v2):
  return math.acos(dotproduct(v1, v2) / (length(v1) * length(v2)))

print ('Угол между векторами: (math): ', np.degrees(_angle(vector1,vector2)))



Угол между векторами (numpy) : 97.71028539649512
Угол между векторами: (math) 97.71028539649512


13. Найти скалярное произведение между векторам x и у 

In [73]:
vector1 = [-1,1,2,3]
vector2 = [0,1,-5,16]

dot_product = np.dot(vector1, vector2)

print ('Скалярное произведение векторов:',dot_product)

39


14. Найти скалярное произведение между векторам x и у

In [74]:
vector1 = [9,-2,4]
vector2 = [2,-5,2]

dot_product = np.dot(vector1, vector2)


print ('Скалярное произведение векторов:',dot_product)

Скалярное произведение векторов: 36


15. Записать вектор X в базисе {b1,b2}

   

In [86]:
a = np.array([[1,-2],[2,3]])
b = np.array([[-1,1],[2,1]])

x = np.array([3,1])

det_a = LA.det(a)
det_b = LA.det(b)

print ('Проверка на детерминант',det_a,det_b)

# Найти обратную матрицу перехода от базиса а к базису b   P = inv(a)b

P = np.matmul(LA.inv(a),b)

# Найти координаты x в базисе b    Xb = inv(P)Xa

x_ = np.matmul(LA.inv(P),x)

print ('Координаты вектора X в базисе b: ',x_)



Проверка на детерминант 7.000000000000001 -2.9999999999999996
Координаты вектора X в базисе b:  [2.66666667 3.66666667]


16. Найти x в базисе E

In [90]:
e = np.array([[1,0,0],[0,1,0],[0,0,1]])  # стандартный базис
e_ = np.array([[1,0,1],[-1,-1,0],[-1,0,3]])

x = np.array([5,-7,8])

det_a = LA.det(e)
det_b = LA.det(e_)

print ('Проверка на детерминант',det_a,det_b)

# Найти обратную матрицу перехода от базиса а к базису b   P = inv(a)b

P = np.matmul(LA.inv(e),e_)

# Найти координаты x в базисе b    Xb = inv(P)Xa

x_ = np.matmul(LA.inv(P),x)

print ('Координаты вектора x в базисе e_: ',x_)


Проверка на детерминант 1.0 -4.0
Координаты вектора X в базисе b:  [1.75 5.25 3.25]


17. Найдите S^2, где S длина вектора в Эвклидовом пространстве

In [97]:
point_1 = np.array([0,0,0,0])
point_2 = np.array([2,-1,4,-1])

distance = np.sqrt(np.dot(point_1-point_2, point_1-point_2))
print(distance**2)

22.0
